name: EternalOS GSI Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Crave and Build
      env:
        CRAVE_USERNAME: ${{ secrets.CRAVE_USERNAME }}
        CRAVE_TOKEN: ${{ secrets.CRAVE_TOKEN }}
      run: |
        curl -L https://github.com -o crave && chmod +x crave
        printf '%s\n' '{"Authorization": "'"$CRAVE_TOKEN"'", "User-Agent": "Crave", "projects": [], "server": "https://foss.crave.io/api"}' > crave.conf
        ./crave repo init -u https://github.com -b main -m default.xml && ./crave repo sync
        ./crave run -- ". build/envsetup.sh && lunch aosp_arm64-trunk_food-userdebug && make systemimage -j\$(nproc)"
