name: EternalOS Crave GSI Sync

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Crave CLI & Auth Secrets
        run: |
          curl -sL https://raw.githubusercontent.com/accupara/crave/refs/heads/master/get_crave.sh -o get_crave.sh
          bash get_crave.sh
          sudo chmod +x crave
          sudo mv crave /usr/local/bin/crave

          mkdir -p ~/.crave
          cat <<EOF > ~/.crave/crave.conf
          {
            "username": "${{ secrets.CRAVE_USERNAME }}",
            "auth_token": "${{ secrets.CRAVE_TOKEN }}"
          }
          EOF

      - name: Generate Local Crave Config
        run: |
          # Generates the config file on the VM right before Crave reads it
          cat <<EOF > crave.yaml
          los21:
            ignoreClientHostname: true
          EOF

      - name: Sync EternalOS 1.5 Source
        run: |
          crave run -- "rm -rf .repo/local_manifests .repo/manifests && /opt/crave/resync.sh https://github.com/${{ github.repository }}.git main"
